# Generated by Django 3.0.3 on 2020-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_code_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
