# Generated by Django 3.0.3 on 2020-03-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtail_code_blog', '0002_auto_20200302_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='background_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
