# Generated by Django 3.0.3 on 2020-03-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_code_blog', '0003_auto_20200307_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='background_color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
